# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- bash: echo "Building!!!..."
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- script: dotnet test
  displayName: 'dotnet test'
- bash: echo "Testing!..."

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*.csproj'
    arguments: 'code coverage'
    testRunTitle: 'TitleTest'

- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      echo $(buildConfiguration)
      echo Hello world)